# Generated by Django 2.2 on 2020-08-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_auto_20200808_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryperson',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
